name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

  permissions:
  contents: read
  packages: write

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install HTMLHint
        run: npm install -g htmlhint
      - name: Run Linter
        run: htmlhint "**/*.html"

  build:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
